services:
  - type: web
    name: flower-ecosystem
    runtime: node
    plan: free
    buildCommand: npm install && mkdir -p uploads
    startCommand: node db-init.js && node server.js
    healthCheckPath: /api/products?limit=1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PG_HOST
        fromDatabase:
          name: flower-db
          property: host
      - key: PG_PORT
        fromDatabase:
          name: flower-db
          property: port
      - key: PG_DATABASE
        fromDatabase:
          name: flower-db
          property: database
      - key: PG_USER
        fromDatabase:
          name: flower-db
          property: user
      - key: PG_PASSWORD
        fromDatabase:
          name: flower-db
          property: password
      - key: JWT_SECRET
        value: "3c0815b1b8bd7063f6ce34756259a00a63a80fc4ad23b5aeff49c095426c6a8271ee3365c2380bfe023098bd0a7a8570f3639fca7c0bd103eb250456ff24fe83"
      - key: JWT_REFRESH_SECRET
        value: "696acde5b6b99d65a05dfad2c2e90ee246f667114fb39990023dbc495779a8ef3e11e63d7d3a2ce49bef409914b2d12ecf759a4b7b5b152976c24b1861ec71a5"
      - key: ADMIN_PASSWORD
        value: "Nharnah@12345"
      - key: SUPERADMIN_PASSWORD
        value: "Super@12345!"
      - key: CORS_ORIGIN
        value: https://flower-ecosystem.onrender.com
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

databases:
  - name: flower-db
    plan: free
    databaseName: flower_ecosystem
