const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '..', '.env') });
const { Pool } = require('pg');
const fs = require('fs');

const pool = new Pool({
    host: process.env.PG_HOST || 'localhost',
    port: parseInt(process.env.PG_PORT || '5432'),
    database: process.env.PG_DATABASE || 'flower_ecosystem',
    user: 'postgres',
    password: process.env.PG_PASSWORD || '',
});

function readJSON(name) {
    return JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'data', name + '.json'), 'utf8'));
}

async function run() {
    // Get course ID mapping (title -> uuid)
    const coursesRes = await pool.query('SELECT id, title FROM learning.courses');
    const courseMap = {};
    for (const r of coursesRes.rows) courseMap[r.title] = r.id;

    const lessons = [
        { course: 'Flower Arrangement Basics', title: 'Introduction to Flower Arrangement', content: "Welcome to Flower Arrangement Basics! In this introductory lesson, we'll explore the history and principles of floral design. You'll learn about the essential tools every florist needs, how to set up your workspace, and the core concepts that will guide your arrangements. We'll cover the elements of design — line, form, space, texture, and color — and how they work together to create visual harmony. By the end of this lesson, you'll understand the foundational vocabulary and concepts that professional florists use every day.", video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', sort_order: 1 },
        { course: 'Flower Arrangement Basics', title: 'Choosing the Right Flowers', content: "Selecting the perfect blooms is the most important step in any arrangement. This lesson teaches you how to evaluate flower freshness, choose seasonal varieties, match flowers to occasions, and build a color palette. You'll learn what to look for when buying from suppliers — petal condition, stem strength, leaf health, and bud stage. We'll also discuss flower sourcing, seasonality charts, and how to select complementary textures and shapes for dynamic arrangements.", video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', sort_order: 2 },
        { course: 'Flower Arrangement Basics', title: 'Basic Arrangement Techniques', content: "Hands-on techniques for building your first arrangement. Learn spiral bouquet construction, vase placement, foliage layering, and balance creation. We'll demonstrate the classic hand-tied bouquet method, proper stem cutting angles, and how to create depth and dimension. You'll practice with different container types and understand how the vessel shape affects your design. Master the fundamentals of anchoring, radial placement, and the golden ratio in floral design.", video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', sort_order: 3 },
        { course: 'Flower Arrangement Basics', title: 'Color Theory for Florists', content: "Color is the most powerful tool in a florist's palette. This lesson dives deep into color theory — the color wheel, complementary schemes, analogous palettes, monochromatic designs, and seasonal color trends. Learn how to create mood and emotion through color choices, how to work with challenging colors, and when to break the rules. Real-world examples of award-winning arrangements will illustrate each concept.", video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', sort_order: 4 },
        { course: 'Flower Arrangement Basics', title: 'Creating Centerpieces', content: "Centerpieces are the heart of event floral design. This lesson covers low and high centerpiece construction, candle integration, table proportion guidelines, and creating visual impact within budget constraints. You'll learn to design for different table shapes, height requirements, and venue styles. We'll also discuss working with clients to understand their vision and translating that into a stunning centerpiece design.", video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', sort_order: 5 },
        { course: 'Flower Arrangement Basics', title: 'Final Project — Build Your Own Bouquet', content: "Apply everything you've learned by creating your own original bouquet. This final project walks you through the complete process — from concept sketch and flower selection to construction and presentation. Submit your final arrangement for peer and instructor feedback. This project is designed to showcase your understanding of all course concepts and produce a portfolio-worthy piece.", video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', sort_order: 6 },
        { course: 'Natural vs Artificial Flowers', title: 'Understanding Flower Types', content: "Learn the four main categories of flowers used in modern floristry: natural fresh-cut, artificial silk/polyester, preserved stabilized, and dried/natural-dried. Each type has unique characteristics, care requirements, and best-use scenarios. We'll examine real samples side-by-side and discuss how to identify each type through visual inspection, touch, and scent.", video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', sort_order: 1 },
        { course: 'Natural vs Artificial Flowers', title: 'Visual Identification Guide', content: "Train your eye to spot the differences between flower types. This lesson covers petal texture analysis, stem construction examination, color uniformity testing, and fragrance evaluation. You'll learn the telltale signs of artificial flowers (wire stems, fabric petals, uniform coloring) versus natural indicators (irregular petal patterns, natural fragrance variations, organic stem textures).", video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', sort_order: 2 },
        { course: 'Natural vs Artificial Flowers', title: 'Authenticity Testing Methods', content: "Professional methods for authenticating flower quality and type. Learn water tests, burn tests for fabric flowers, touch and feel evaluation, and microscope examination techniques. Understand how to verify preserved flower claims, test dye quality in dried flowers, and distinguish high-end silk from natural blooms. These skills are essential for buyers, collectors, and quality control professionals.", video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', sort_order: 3 },
        { course: 'Natural vs Artificial Flowers', title: "Buyer's Guide & Checklist", content: "Practical checklist for evaluating flowers before purchase. Covers supplier vetting, sample request procedures, quality scoring systems, and documentation best practices. You'll leave with a downloadable evaluation template you can use for every flower purchase, whether you're buying for personal use, resale, or event production.", video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', sort_order: 4 },
        { course: 'Wedding Floristry Masterclass', title: 'Wedding Consultation & Planning', content: "Learn how to conduct professional wedding consultations, understand client vision, create mood boards, and develop comprehensive wedding flower plans. Covers budget estimation, timeline creation, and vendor coordination.", video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', sort_order: 1 },
        { course: 'Wedding Floristry Masterclass', title: 'Bridal Bouquet Construction', content: "Master the art of the bridal bouquet — from classic round and cascading to modern composite and hand-tied styles. Learn wiring, taping, ribbon wrapping, and handle finishing techniques.", video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', sort_order: 2 },
        { course: 'Wedding Floristry Masterclass', title: 'Ceremony & Arch Installations', content: "Design stunning ceremony backdrops, arch installations, aisle decorations, and altar arrangements. Learn structural engineering for freestanding designs, attachment techniques, and venue-specific considerations.", video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', sort_order: 3 },
        { course: 'Wedding Floristry Masterclass', title: 'Reception Table Designs', content: "Comprehensive guide to reception floral design including head table, guest tables, cake table, and lounge area arrangements. Covers height guidelines, sight-line considerations, and cohesive theme execution.", video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', sort_order: 4 },
        { course: 'Wedding Floristry Masterclass', title: 'Boutonnieres & Corsages', content: "Learn the delicate art of creating boutonnieres, corsages, and personal flowers for the wedding party. Techniques for working with delicate blooms, attaching to different fabrics, and ensuring all-day wearability.", video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', sort_order: 5 },
        { course: 'Wedding Floristry Masterclass', title: 'Wedding Day Execution', content: "How to manage wedding day delivery, setup, and breakdown. Covers logistics planning, team coordination, emergency kits, timing schedules, and handling last-minute changes with grace.", video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', sort_order: 6 },
        { course: 'Wedding Floristry Masterclass', title: 'Pricing & Packages', content: "Develop profitable wedding flower packages. Learn cost calculation, markup strategies, package tiering, contract terms, deposit structures, and how to communicate value to clients effectively.", video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', sort_order: 7 },
        { course: 'Wedding Floristry Masterclass', title: 'Portfolio & Marketing', content: "Build a compelling wedding florist portfolio and market your services. Covers professional photography, social media strategy, vendor networking, bridal show participation, and winning client proposals.", video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', sort_order: 8 },
        { course: 'Flower Care & Preservation', title: 'Daily Flower Care Routine', content: "Essential daily care practices for cut flowers and potted plants. Covers proper watering techniques, stem recutting schedules, leaf management, and environmental factors that affect flower longevity.", video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', sort_order: 1 },
        { course: 'Flower Care & Preservation', title: 'Homemade Flower Food Recipes', content: "Learn professional flower food formulas you can make at home. Covers sugar-acid-bleach ratios, commercial additive comparisons, and species-specific nutrition requirements.", video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', sort_order: 2 },
        { course: 'Flower Care & Preservation', title: 'Drying & Pressing Methods', content: "Comprehensive guide to preserving flowers through air drying, silica gel, pressing, and microwave methods. Each technique is demonstrated with step-by-step instructions for best results.", video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', sort_order: 3 },
        { course: 'Flower Care & Preservation', title: 'Resin Preservation Art', content: "Create stunning jewelry, paperweights, and keepsakes using resin-encased preserved flowers. Learn mold selection, resin mixing, bubble removal, curing, and finishing techniques.", video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', sort_order: 4 },
        { course: 'Flower Care & Preservation', title: 'Long-Term Storage Solutions', content: "Professional techniques for storing dried and preserved flowers long-term. Covers climate control, pest prevention, UV protection, packaging methods, and inventory rotation systems.", video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', sort_order: 5 },
        { course: 'Floristry Business Startup', title: 'Writing Your Business Plan', content: "Create a comprehensive floristry business plan from scratch. Covers market analysis, target audience definition, competitive positioning, financial projections, and growth milestones. Includes downloadable business plan templates.", video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', sort_order: 1 },
        { course: 'Floristry Business Startup', title: 'Pricing Products & Services', content: "Master floristry pricing strategies. Learn cost-plus pricing, value-based pricing, seasonal pricing adjustments, and how to price for profit. Covers material costs, labor calculations, overhead allocation, and competitive analysis.", video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', sort_order: 2 },
        { course: 'Floristry Business Startup', title: 'Sourcing Suppliers', content: "Find and evaluate flower suppliers, wholesale markets, and direct-from-grower options. Learn negotiation tactics, quality assessment, minimum order strategies, and building long-term supplier relationships.", video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', sort_order: 3 },
        { course: 'Floristry Business Startup', title: 'Selling Flowers Online', content: "Set up your online flower selling presence. Covers e-commerce platforms, product photography, delivery logistics, packaging for shipping, and digital marketing strategies to attract online customers.", video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', sort_order: 4 },
        { course: 'Floristry Business Startup', title: 'Scaling Your Business', content: "Strategies for growing your floral business beyond the startup phase. Covers hiring, wholesale accounts, event contracts, corporate clients, franchise opportunities, and building a team.", video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', sort_order: 5 },
        { course: 'Growing Roses from Seed to Bloom', title: 'Soil Preparation & Planting', content: "Prepare the perfect soil mix for roses. Learn about pH levels, drainage requirements, organic matter additions, and container vs ground planting. Covers seed starting techniques, transplanting, and initial care routines.", video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', sort_order: 1 },
        { course: 'Growing Roses from Seed to Bloom', title: 'Watering & Feeding Schedules', content: "Establish proper watering and feeding routines for healthy roses. Covers deep watering techniques, drip irrigation setup, organic and synthetic fertilizer options, and seasonal feeding schedules.", video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', sort_order: 2 },
        { course: 'Growing Roses from Seed to Bloom', title: 'Pruning & Training Techniques', content: "Master rose pruning for maximum blooms and plant health. Learn deadheading, selective pruning, climbing rose training, and seasonal pruning calendars. Includes diagrams for proper cut placement.", video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', sort_order: 3 },
        { course: 'Growing Roses from Seed to Bloom', title: 'Pest & Disease Management', content: "Identify and manage common rose pests and diseases. Covers aphids, black spot, powdery mildew, Japanese beetles, and organic pest control methods. Learn integrated pest management strategies.", video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', sort_order: 4 },
        { course: 'Growing Roses from Seed to Bloom', title: 'Seasonal Care Calendar', content: "Month-by-month care guide for rose gardens. Covers spring pruning, summer deadheading, fall preparation, winter protection, and regional climate considerations for optimal rose health year-round.", video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', sort_order: 5 },
    ];

    let total = 0;
    for (const l of lessons) {
        const courseId = courseMap[l.course];
        if (!courseId) {
            console.warn(`  Skipping "${l.title}" — course "${l.course}" not found`);
            continue;
        }
        await pool.query(
            'INSERT INTO learning.lessons (course_id, title, content, video_url, sort_order) VALUES ($1, $2, $3, $4, $5)',
            [courseId, l.title, l.content, l.video_url, l.sort_order]
        );
        total++;
    }
    console.log(`Done — inserted ${total} lessons across ${Object.keys(courseMap).length} courses`);
    await pool.end();
}
run().catch(e => { console.error(e); process.exit(1); });
